### ISSUE TITLE
Falha ao gerar CPF/CNPJ incorreto

### ISSUE THREAD

**Issue by allgood** [jansenfelipe/faker-br#4]
O método `shuffleString` não é suficiente para garantir que uma chamada às funções com o parâmetro `$verdadeiro = false` gerem um número que não passa pelos validadores.

Em várias execuções, algumas vezes acaba gerando um número válido, mesmo não sendo essa a intenção, dificultando testes de validadores.

**Comment by jansenfelipe** [comment]
#5
